# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/premium_adventure?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT configuration
jwt.secret=9a67475d459d0287311185590c8839088825851416807cc902d1d4d732860a22
jwt.expiration=86400000

# Server configuration
server.port=8080

# Federal Bank Demo Configuration
federalbank.merchant.id=FEDERAL_DEMO_MERCHANT
federalbank.access.code=FEDERAL_DEMO_ACCESS
federalbank.working.key=12345678901234567890123456789012
federalbank.payment.url=https://sandbox.federalbank.co.in/mock-payment

# Razorpay Configuration
razorpay.key.id=rzp_test_SgqwRbbG5qnBvy
razorpay.key.secret=tdmDdyR7jVKUWgpraxDVx2AG
