# Database configuration
spring.datasource.url=${MYSQL_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:root}

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT configuration
jwt.secret=${JWT_SECRET:9a67475d459d0287311185590c8839088825851416807cc902d1d4d732860a22}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Server configuration
server.port=${PORT:8080}

# Razorpay Configuration
razorpay.key.id=${RAZORPAY_KEY_ID:rzp_test_SgqwRbbG5qnBvy}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:tdmDdyR7jVKUWgpraxDVx2AG}
